### ISSUE TITLE
Add loop-unrolling compilation pass

### ISSUE THREAD

**Issue by elenbaasc** [QuTech-Delft/OpenSquirrel#120]
At some point the language (cQASM 3) will be able to support control flow operations (e.g. loops). Instead of unrolling loops in each Exporter separately (as these lower languages generally don't support control flow) these loops will need to be unrolled before the exporter pass (or when another compiler pass requires unrolling to take place).

**Comment by rturrado** [comment]
@elenbaasc can you add a comment on why this task is closed as completed?
