### ISSUE TITLE
Add constant folding pass

### ISSUE THREAD

**Issue by elenbaasc** [QuTech-Delft/OpenSquirrel#121]
Constant folding required because certain backend (languages) will not be able to evaluate certain complex expressions. This is generally done early in the compilation strategy.

**Comment by arcturusannamalai** [comment]
Can you elaborate more? What are the optimization opportunity for quantum circuit ? Is it like a double application of a gate etc. ? Or what's the scenario where you see the breakdown of current technique ?

**Comment by rturrado** [comment]
A quantum algorithm will contain also some classical code, concretely arithmetic operations. The constant folding pass is a typical classical compiler optimization where you just reduce branches of the AST from an arithmetic operation that can be evaluated in compile time, e.g., 5*sin(pi), to its evaluated value, e.g., -5.

**Comment by arcturusannamalai** [comment]
@rturrado - I understand the classical portion quite well; I'm not sure how in the QASM / reversible circuit concept of the Quantum algorithms we may encounter constant folding. An example algorithm maybe useful to see.

**Comment by rturrado** [comment]
Sure, an example may be:

```
