### ISSUE TITLE
HectoQubit: Use target info to (re)name qubits

### ISSUE THREAD

**Issue by elenbaasc** [QuTech-Delft/OpenSquirrel#137]
The HectoQubit backend provides target info to QI. Here the names of the qubits are defined. These need to be mapped on the qubit references in the cqasm/Quantify Schedule program.

Special care needs to be taken with regard to tracking where the measurement outcomes of the respective qubits are stored.

**Comment by rturrado** [comment]
@elenbaasc can you add a comment on why this task is closed as completed?
