### ISSUE TITLE
Fix namespaces to avoid `opensquirrel.squirrel_ir.Gate`

### ISSUE THREAD

**Issue by pablolh** [QuTech-Delft/OpenSquirrel#87]

**Comment by pablolh** [comment]
Should we rename the `squirrel_ir` to just `ir` since it's already in the `opensquirrel` module?
Should we import things like `Gate`, `BlochSphereRotation` ... which are user-facing, to the `opensquirrel` "namespace" so that the user doesn't have to use the `ir` module?

**Comment by elenbaasc** [comment]
I think that's a good idea. Unless there will be other IRs, I don't see a good reason to prefix it with `squirrel_`.

Also since this is an issue now, we should remove the note from the tutorial.

**Comment by rturrado** [comment]
This may be already done as part of PR #198.

**Comment by arcturusannamalai** [comment]
I think this should be closed as well

**Comment by rturrado** [comment]
Indeed, thanks. This is nowadays `opensquirrel.ir.Gate`.
